import type { Metadata } from 'next';

import { Open_Sans } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';

import QueryClientProvider from '@/providers/query-client-provider';
import { SessionProvider } from '@/providers/session-provider';
import { getAccessTokenFromServer } from '@/utils/auth';

const font = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const token = await getAccessTokenFromServer();

  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${font.variable} antialiased`}>
        <SessionProvider token={token}>
          <QueryClientProvider>{children}</QueryClientProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
