name: 'Web app: Build and deploy'

on:
  push:
    branches:
      - main
env:
  IMAGE_NAME: qwitix-web
  TAG: latest
  TARGET_DIR: ./qwitix-infra

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create .env file from secrets
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Container registry login
        run: az acr login --name ${{ secrets.CONTAINER_NAME }}

      - name: Build and push to Azure Container Registry
        working-directory: ./
        run: |
          docker compose --env-file .env build ${{ env.IMAGE_NAME }}
          docker tag ${{ env.IMAGE_NAME }} ${{ secrets.CONTAINER_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          docker push ${{ secrets.CONTAINER_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: development

    steps:
      - name: Deploy to VM
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ${{ env.TARGET_DIR }} &&
            sudo az acr login --name ${{ secrets.CONTAINER_NAME }} &&
            sudo docker compose pull &&
            sudo docker compose up -d &&
            sudo docker system prune -f
